payment_valueCREATE TABLE customers (
    customer_id TEXT PRIMARY KEY,
    customer_unique_id TEXT,
    customer_zip_code_prefix INTEGER,
    customer_city TEXT,
    customer_state VARCHAR(2)
);

select * from customers


CREATE TABLE orders (
    order_id TEXT PRIMARY KEY,
    customer_id TEXT,
    order_status TEXT,
    order_purchase_timestamp TIMESTAMP,
    order_approved_at TIMESTAMP,
    order_delivered_carrier_date TIMESTAMP,
    order_delivered_customer_date TIMESTAMP,
    order_estimated_delivery_date TIMESTAMP
);


select * from orders



CREATE TABLE order_items (
    order_id TEXT,
    order_item_id INTEGER,
    product_id TEXT,
    seller_id TEXT,
    shipping_limit_date TIMESTAMP,
    price NUMERIC(10,2),
    freight_value NUMERIC(10,2),

    PRIMARY KEY (order_id, order_item_id),

    FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);

select *  from order_items



CREATE TABLE order_payments (
    order_id TEXT,
    payment_sequential INTEGER,
    payment_type TEXT,
    payment_installments INTEGER,
    payment_value NUMERIC(10,2),

    PRIMARY KEY (order_id, payment_sequential),

    FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


select * from order_payments


DROP TABLE IF EXISTS order_reviews;
CREATE TABLE order_reviews (
    review_id TEXT,
    order_id TEXT,
    review_score INTEGER,
    review_comment_title TEXT,
    review_comment_message TEXT,
    review_creation_date TIMESTAMP,
    review_answer_timestamp TIMESTAMP,

    PRIMARY KEY (review_id, order_id),

    FOREIGN KEY (order_id)
        REFERENCES orders(order_id)
);


select * from order_reviews



CREATE TABLE products (
    product_id TEXT PRIMARY KEY,
    product_category_name TEXT,
    product_name_length INTEGER,
    product_description_length INTEGER,
    product_photos_qty INTEGER,
    product_weight_g INTEGER,
    product_length_cm INTEGER,
    product_height_cm INTEGER,
    product_width_cm INTEGER
);

select * from products


SELECT COUNT(*) AS total_products
FROM products;

SELECT
    product_category_name,
    COUNT(*) AS product_count
FROM products
GROUP BY product_category_name
ORDER BY product_count DESC
LIMIT 15;


CREATE TABLE sellers (
    seller_id TEXT PRIMARY KEY,
    seller_zip_code_prefix INTEGER,
    seller_city TEXT,
    seller_state VARCHAR(2)
);


SELECT COUNT(*) AS total_sellers
FROM sellers;

SELECT
    seller_state,
    COUNT(*) AS seller_count
FROM sellers
GROUP BY seller_state
ORDER BY seller_count DESC;


CREATE TABLE product_category_translation (
    product_category_name TEXT PRIMARY KEY,
    product_category_name_english TEXT
);

select * from product_category_translation


SELECT COUNT(*) AS total_categories
FROM product_category_translation;



SELECT *
FROM product_category_translation
LIMIT 20;


CREATE TABLE geolocation (
    geolocation_zip_code_prefix INTEGER,
    geolocation_lat NUMERIC(10,7),
    geolocation_lng NUMERIC(10,7),
    geolocation_city TEXT,
    geolocation_state VARCHAR(2)
);

SELECT COUNT(*) AS total_geolocation_records
FROM geolocation;


SELECT
    geolocation_state,
    COUNT(*) AS location_records
FROM geolocation
GROUP BY geolocation_state
ORDER BY location_records DESC;


''' PART 1 — CEO Executive Analysis
“How is the business performing overall?”

Question 1 — How many orders, customers, 
products, and sellers does the platform have?
'''

SELECT
    (SELECT COUNT(*) FROM orders) AS total_orders,
    (SELECT COUNT(*) FROM customers) AS total_customers,
    (SELECT COUNT(*) FROM products) AS total_products,
    (SELECT COUNT(*) FROM sellers) AS total_sellers;


'''

Question 2 — What is the total revenue 
generated by the business?
'''

SELECT
    ROUND(SUM(price), 2) AS total_revenue
FROM order_items;


'''
Question 3 — What is the total 
freight/shipping cost paid by customers?'''

select * from order_items

SELECT
    ROUND(SUM(freight_value), 2) AS total_freight_revenue
FROM order_items;


'''
Question 4 — What is the average order value?
'''

SELECT
    ROUND(SUM(price) / COUNT(DISTINCT order_id), 2) AS average_order_value
FROM order_items;


'''
Question 5 — How many orders are successfully 
delivered, canceled, or otherwise incomplete?
'''

select * from orders

select "order_status" , count(*) as "orders_delivered_status",
ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),
        2
    ) AS percentage
from orders
group by "order_status"
ORDER BY "orders_delivered_status" DESC;


'''
Question 6 — What is the monthly revenue trend?
'''

select * from orders
select * from order_items


select date_trunc('month' , o."order_purchase_timestamp") as month,
round(sum(oi.price),2) as revenue
from orders o
join order_items oi
on o.order_id=oi.order_id
where o.order_status='delivered'
group by month
order by month


'''
Q7. Which months generated the highest revenue?
'''

select date_trunc('month',o."order_purchase_timestamp") as month,
round(sum(oi.price),2) as revenue
from orders o
join order_items as oi
on o.order_id=oi.order_id
where o.order_status='delivered'
group by month
order by month desc
limit 10



'''
Q8. Which product categories generate the most revenue?
'''

select * from products


SELECT
    p.product_category_name AS product_category,
    ROUND(SUM(oi.price), 2) AS revenue
FROM products AS p
JOIN order_items AS oi
    ON p.product_id = oi.product_id
JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY revenue DESC
LIMIT 10;


'''
Q9. Which categories have the highest order volume?
'''


SELECT
    p.product_category_name AS product_category,
    count(distinct(oi.order_id)) AS "total_orders"
FROM products AS p
JOIN order_items AS oi
    ON p.product_id = oi.product_id
JOIN orders AS o
    ON oi.order_id = o.order_id
WHERE o.order_status = 'delivered'
GROUP BY p.product_category_name
ORDER BY "total_orders" DESC
LIMIT 10;


'''
Q10. Which sellers generate the highest revenue?
'''

select * from order_items

select oi.seller_id,
round(sum(oi.price),2) as revenue
from order_items oi
join orders o
on o.order_id=oi.order_id
where o.order_status='delivered'
group by seller_id
order by revenue desc
limit 10


'''
Q12: Which sellers have the highest number of orders?
'''

select "seller_id", count("order_id") as
"Total number of orders"
from order_items
group by "seller_id"
order by "Total number of orders" desc
limit 10


'''
Q13: Which states generate the most revenue?
'''


select c.customer_state,
round(sum(oi.price),2) as revenue
from customers c
join orders o 
on c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_state
order by "revenue" desc

'''
Q14: Which states have the highest number of customers?
'''

select "customer_state",
count("customer_id") as "total customers"
from customers
group by "customer_state"
order by "total customers" desc
limit 5


'''
Q15: What is the average delivery time?
'''

select  * from orders

SELECT AVG(
"order_delivered_customer_date"::date - "order_purchase_timestamp"::date
) AS avg_delivery_days
FROM orders
WHERE "order_delivered_customer_date" IS NOT NULL;



'''
Q16: Which categories have the longest delivery time?
'''


select p.product_category_name,
(o.order_delivered_customer_date::date - o.order_purchase_timestamp::date)
as "delivery time"
from products p
join order_items oi 
on  p.product_id=oi.product_id
join orders o
on o.order_id=oi.order_id
WHERE o.order_delivered_customer_date IS NOT NULL
order by "delivery time" desc
limit 10

'''
Q17: How does freight cost affect order value?
'''

SELECT
CORR("price", "freight_value") AS correlation
FROM order_items;


'''
Q18: Which payment methods are most commonly used?
'''
select * from order_items

select "payment_type",count("payment_type") as "payment method used"
from order_payments
group by "payment_type" 
order by "payment method used" desc

'''
Q19: What is the relationship between payment 
installments and order value?
'''

SELECT
CORR(p.payment_installments, oi.price) AS correlation
from order_payments p
join order_items oi
on p.order_id=oi.order_id


'''
Q20: Which categories have the highest review scores?
'''

select * from order_reviews

select p.product_category_name,
sum(r.review_score) as "review_score"
from products p
join order_items oi
on p.product_id=oi.product_id
join order_reviews r
on
oi.order_id=r.order_id
group by p.product_category_name
order by "review_score" desc


'''
Q21 — Revenue by Customer State

Business question:

Which customer states generate the highest revenue?
'''

select c.customer_state,
round(sum(oi.price),2) as "revenue"
from customers c 
join orders o on
c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_state
order by "revenue" desc
limit 10


'''
Q22 — Average Order Value by State

Which customer states have the highest average order value?
'''

select c.customer_state,
round(avg(oi.price),2) as "avg_order_price"
from customers c 
join orders o on
c.customer_id=o.customer_id
join order_items oi
on o.order_id=oi.order_id
group by c.customer_state
order by "avg_order_price" desc
limit 10


'''
Q23 — Repeat vs One-Time Customers

How many customers placed only one order versus multiple orders?
'''

SELECT
c.customer_id,
COUNT(o.order_id) AS order_count
FROM customers c
join orders o
on c.customer_id=o.customer_id
GROUP BY c.customer_id;


SELECT
"customer_id",
COUNT(*) AS "total_orders"
FROM orders
GROUP BY "customer_id"
ORDER BY "total_orders" DESC;



WITH customer_orders AS (
SELECT
customer_id,
COUNT(*) AS order_count
FROM orders
GROUP BY customer_id
)
SELECT
CASE
WHEN order_count = 1 THEN 'One-Time Customer'
ELSE 'Repeat Customer'
END AS customer_type,
COUNT(*) AS customer_count
FROM customer_orders
GROUP BY customer_type;


'''
Q25 — Monthly Customer Growth

How has the number of unique customers changed month by month?

Business growth trend.
'''

SELECT
DATE_TRUNC('month', order_purchase_timestamp) AS month,
COUNT(DISTINCT customer_id) AS unique_customers
FROM orders
GROUP BY DATE_TRUNC('month', order_purchase_timestamp)
ORDER BY month desc;


'''
Q26 — Monthly Order Growth

How has the number of delivered orders changed month by month?'''

select count("order_id") as "no of orders delivered",
date_trunc('month',"order_delivered_customer_date") as "month"
from orders
where "order_status"='delivered'
group by "month"
order by "month"


'''
Q27 — Revenue vs Freight Cost by Category

Which product categories generate high revenue but 
also have high freight costs?
'''

select p.product_category_name,
sum(oi.price) as "revenue",
sum(oi.freight_value) as "freight cost"
from products p
join order_items oi
on p.product_id=oi.product_id
group by p.product_category_name
order by "revenue" desc 
